# Generated by Django 2.2.7 on 2019-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191207_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
