# Generated by Django 2.2.7 on 2019-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='items_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
