# Generated by Django 2.2.7 on 2019-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_checkout_items_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='items_json',
            new_name='itemsJson',
        ),
    ]
