# Generated by Django 2.2.7 on 2019-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191208_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='itemsJson',
            new_name='itemsjson',
        ),
    ]
